import React from 'react';
import { Icon } from '../ui-elements/Icon';

export const Icons = {
  Check: (props: any) => <Icon name="check" size="sm" {...props} />,
  User: (props: any) => <Icon name="person" size="sm" {...props} />,
  Chart: (props: any) => <Icon name="bar_chart" size="sm" {...props} />,
  Bell: (props: any) => <Icon name="notifications" size="sm" {...props} />,
  Search: (props: any) => <Icon name="search" size="sm" {...props} />,
  Menu: (props: any) => <Icon name="menu" size="md" {...props} />,
  Star: (props: any) => <Icon name="star" size="sm" {...props} />,
  Settings: (props: any) => <Icon name="settings" size="sm" {...props} />,
  Chat: (props: any) => <Icon name="chat_bubble_outline" size="sm" {...props} />,
  Folder: (props: any) => <Icon name="folder" size="md" {...props} />,
  File: (props: any) => <Icon name="description" size="md" {...props} />,
  Send: (props: any) => <Icon name="send" size="sm" {...props} />,
  More: (props: any) => <Icon name="more_vert" size="sm" {...props} />,
  ChevronDown: (props: any) => <Icon name="expand_more" size="sm" {...props} />,
  ChevronRight: (props: any) => <Icon name="chevron_right" size="sm" {...props} />,
  Image: (props: any) => <Icon name="image" size="lg" {...props} />,
  Help: (props: any) => <Icon name="help_outline" size="sm" {...props} />,
  Edit: (props: any) => <Icon name="edit" size="sm" {...props} />,
  Trash: (props: any) => <Icon name="delete_outline" size="sm" {...props} />,
  Lock: (props: any) => <Icon name="lock" size="sm" {...props} />,
  Cloud: (props: any) => <Icon name="cloud_upload" size="md" {...props} />,
  Calendar: (props: any) => <Icon name="calendar_today" size="sm" {...props} />,
  Clock: (props: any) => <Icon name="schedule" size="sm" {...props} />,
  Attach: (props: any) => <Icon name="attach_file" size="sm" {...props} />,
  Link: (props: any) => <Icon name="link" size="sm" {...props} />,
  Flag: (props: any) => <Icon name="flag" size="sm" {...props} />,
  Tag: (props: any) => <Icon name="label" size="sm" {...props} />,
  Close: (props: any) => <Icon name="close" size="sm" {...props} />,
  Code: (props: any) => <Icon name="code" size="sm" {...props} />,
};